package handlers

import (
	"context"
	"errors"

	Authv1 "auth-service/gen/auth/v1" // generated by protoc-gen-go

	"auth-service/database" // Import the database module

	"connectrpc.com/connect"
)

// Login performs user login using phone number and OTP
func (s *AuthServer) ValidatePhoneNumberLogin(
	ctx context.Context,
	req *connect.Request[Authv1.LoginRequest],
) (*connect.Response[Authv1.LoginResponse], error) {
	phoneNumber := req.Msg.PhoneNumber
	otp := req.Msg.Otp

	// Validate OTP
	valid, err := database.ValidateOTP(phoneNumber, otp)
	if err != nil {
		return nil, err
	}
	if !valid {
		return nil, errors.New("invalid credentials")
	}

	// Generate access token (for demonstration purposes, generate a simple token)
	accessToken := generateAccessToken()

	// Return response with access token
	res := connect.NewResponse(&Authv1.LoginResponse{
		AccessToken: accessToken,
	})
	return res, nil
}

// For demonstration purposes, generate a simple access token
func generateAccessToken() string {
	// You can use a more sophisticated method for generating access tokens
	// not in scope
	return "test_access_token"
}
