package handlers

import (
	"context"
	"errors"

	Authv1 "auth-service/gen/auth/v1" // generated by protoc-gen-go

	"auth-service/database" // Import the database module

	"connectrpc.com/connect"
)

// GetProfile retrieves user profile using phone number
func (s *AuthServer) GetProfile(
	ctx context.Context,
	req *connect.Request[Authv1.GetProfileRequest],
) (*connect.Response[Authv1.GetProfileResponse], error) {

	// Check if phone number is provided
	if req.Msg.PhoneNumber == "" {
		return nil, errors.New("phone number is mandatory")
	}

	phoneNumber := req.Msg.PhoneNumber

	// Retrieve profile data from database
	profile, err := database.GetProfileByPhoneNumber(phoneNumber)
	if err != nil {
		return nil, err
	}

	// Create response
	res := connect.NewResponse(&Authv1.GetProfileResponse{
		PhoneNumber: profile.PhoneNumber,
		Email:       profile.Email,
		FirstName:   profile.FirstName,
		LastName:    profile.LastName,
	})
	return res, nil
}
