package handlers

import (
	"context"
	"errors"

	Authv1 "auth-service/gen/auth/v1" // generated by protoc-gen-go

	"auth-service/database" // Import the database module

	"connectrpc.com/connect"
)

// VerifyPhoneNumber verifies user account using phone number and OTP
func (s *AuthServer) LoginWithPhoneNumber(
	ctx context.Context,
	req *connect.Request[Authv1.VerifyPhoneNumberRequest],
) (*connect.Response[Authv1.VerifyPhoneNumberResponse], error) {
	phoneNumber := req.Msg.PhoneNumber
	otp := req.Msg.Otp

	// Validate OTP
	valid, err := database.ValidateOTP(phoneNumber, otp)
	if err != nil {
		return nil, err
	}
	if !valid {
		return nil, errors.New("invalid OTP")
	}

	// Update user account as verified
	err = database.UpdateAccountVerification(phoneNumber)
	if err != nil {
		return nil, err
	}

	// Return success response
	res := connect.NewResponse(&Authv1.VerifyPhoneNumberResponse{
		Message: "Account verified successfully",
		Success: true,
	})
	return res, nil
}
