package handlers

import (
	"context"
	"errors"
	"fmt"

	Authv1 "auth-service/gen/auth/v1" // generated by protoc-gen-go

	"auth-service/database" // Import the database module

	"connectrpc.com/connect"
)

// LoginWithPhoneNumber verifies user account using phone number and OTP
func (s *AuthServer) LoginWithPhoneNumber(
	ctx context.Context,
	req *connect.Request[Authv1.VerifyPhoneNumberRequest],
) (*connect.Response[Authv1.VerifyPhoneNumberResponse], error) {
	// Extract phone number and OTP from the request
	phoneNumber := req.Msg.PhoneNumber
	otp := req.Msg.Otp

	// Validate OTP
	valid, err := database.ValidateOTP(phoneNumber, otp)
	if err != nil {
		fmt.Println("Error validating OTP: ", err)
		return nil, err
	}
	if !valid {
		return nil, errors.New("invalid OTP")
	}

	// Update user account as verified
	if err := database.UpdateAccountVerification(phoneNumber); err != nil {
		fmt.Println("Error updating account verification status: ", err)
		return nil, err
	}

	// Log successful account verification
	fmt.Println("Account verified successfully for phone number: ", phoneNumber)

	// Return success response
	res := connect.NewResponse(&Authv1.VerifyPhoneNumberResponse{
		Message: "Account verified successfully",
		Success: true,
	})
	return res, nil
}
