package main

import (
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"auth-service/gen/auth/v1/authv1connect" // generated by protoc-gen-connect-go
	"auth-service/handlers"
)

func main() {
	Auther := &handlers.AuthServer{}
	mux := http.NewServeMux()
	path, handler := authv1connect.NewAuthServiceHandler(Auther)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
