package main

import (
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"otp-service/gen/otp/v1/otpv1connect" // generated by protoc-gen-connect-go
	"otp-service/handlers"
)

func main() {
	Otper := &handlers.OtpServer{}
	mux := http.NewServeMux()
	path, handler := otpv1connect.NewOtpServiceHandler(Otper)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8081",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
