package main

import (
	"fmt"
	"log"
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"otp-service/gen/otp/v1/otpv1connect" // generated by protoc-gen-connect-go
	"otp-service/handlers"
)

func main() {
	// Set up OTP server
	otper := &handlers.OtpServer{}

	// Set up HTTP multiplexer
	mux := http.NewServeMux()

	// Set up OTP service handler
	path, handler := otpv1connect.NewOtpServiceHandler(otper)
	mux.Handle(path, handler)

	// Configure server address
	serverAddr := ":8081"

	// Use h2c to serve HTTP/2 without TLS
	server := &http.Server{
		Addr:    serverAddr,
		Handler: h2c.NewHandler(mux, &http2.Server{}),
	}

	// Start the server
	fmt.Println("Server started at", serverAddr)
	if err := server.ListenAndServe(); err != nil {
		log.Fatalf("Server error: ", err)
	}
}
